### ISSUE TITLE
Themes preview?

### ISSUE THREAD

**Issue by reiven** [thecodinghouse/mezzanine-themes#3]
Hi!

It will be great if a "preview" of each theme can also be included. At least a screenshot would help

Thanks

**Comment by andriisoldatenko** [comment]
@reiven Done at https://github.com/thecodinghouse/mezzanine-themes/pull/6/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by reiven** [comment]
Great!!! Thanks!
