### ISSUE TITLE
Error with 'future' in template Flat

### ISSUE THREAD

**Issue by alex2lv** [thecodinghouse/mezzanine-themes#4]
Hello,
When I use the "flat" template I have this error :

_Django Version:    1.10
Exception Type:     TemplateSyntaxError
Exception Value:    

'future' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
blog_tags
cache
comment_tags
comments
disqus_tags
fb_csrf
fb_pagination
fb_tags
i18n
keyword_tags
l10n
log
mezzanine_tags
pages_tags
rating_tags
static
staticfiles
twitter_tags
tz_

Error during template rendering
In template /home/alex/Mezzanine/meza/testapp/flat/templates/base.html, error at line 3

future' is not a registered tag library. Must be one of: admin_list admin_modify admin_static admin_urls blog_tags cache comment_tags comments disqus_tags fb_csrf fb_pagination fb_tags i18n keyword_tags l10n log mezzanine_tags pages_tags rating_tags static staticfiles twitter_tags tz

This is error came from this line 
**{% load pages_tags mezzanine_tags i18n future staticfiles %}**

With a Django version 1.9.9 it's works fine

Do you have a workaround ?

**Comment by mikahaht** [comment]
Downgrade into Django 1.9.12 and you will be fine. Django 1.10 made some changes that needs to be sorted out on mezzanine.

**Comment by andriisoldatenko** [comment]
https://github.com/thecodinghouse/mezzanine-themes/pull/5 - fixed

**Comment by abhinavsohani** [comment]
[Merged #5 ](https://github.com/thecodinghouse/mezzanine-themes/pull/5). Thanks @andriisoldatenko
